/**
 * Shiki → CSS classes.
 *
 * Shiki normally writes colors as inline `style="color:#…"` attributes. Those would force
 * `style-src 'unsafe-inline'` in our CSP, so this transformer rewrites every inline style
 * into a class (`.s-<hex>`), and `writeShikiCss()` generates the matching stylesheet from
 * the theme definition at startup. Result: code highlighting with a strict CSP.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { bundledThemes } from 'shiki';

const norm = (c) => c.trim().toLowerCase().replace('#', '');

/** @returns {import('shiki').ShikiTransformer} */
export function styleToClass() {
  return {
    name: 'style-to-class',
    pre(node) {
      delete node.properties.style;
    },
    span(node) {
      const style = node.properties.style;
      if (typeof style !== 'string') return;
      delete node.properties.style;
      const classes = [];
      for (const decl of style.split(';')) {
        const [prop, value] = decl.split(':').map((s) => s?.trim());
        if (!prop || !value) continue;
        if (prop === 'color') classes.push(`s-${norm(value)}`);
        else if (prop === 'font-style' && value === 'italic') classes.push('s-i');
        else if (prop === 'font-weight' && value === 'bold') classes.push('s-b');
        else if (prop === 'text-decoration' && value === 'underline') classes.push('s-u');
      }
      if (classes.length) this.addClassToHast(node, classes);
    },
  };
}

/** Generate the stylesheet for every color the theme can emit. */
export async function writeShikiCss(themeName, outFile) {
  const theme = (await bundledThemes[themeName]()).default;
  const colors = new Set();
  const fg = theme.colors?.['editor.foreground'] ?? theme.fg;
  const bg = theme.colors?.['editor.background'] ?? theme.bg;
  if (fg) colors.add(norm(fg));
  for (const tc of theme.tokenColors ?? []) {
    if (tc.settings?.foreground) colors.add(norm(tc.settings.foreground));
  }
  const lines = [
    `/* Generated by src/integrations/shiki-classes.mjs from theme "${themeName}". Do not edit. */`,
    `.astro-code{--code-bg:#${norm(bg)};--code-fg:#${norm(fg)}}`,
    ...[...colors].sort().map((c) => `.s-${c}{color:#${c}}`),
    '.s-i{font-style:italic}.s-b{font-weight:700}.s-u{text-decoration:underline}',
  ];
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, lines.join('\n') + '\n');
}
